"""Published interface of the Work Core context.

Other contexts import from here and nowhere else inside this package (ADR-0001). Persistence models
are exported for the platform's schema tooling; the domain rules are exported because downstream
contexts (Commitment, Governance) need to reason about work status without reimplementing it.

The application services are the write path, and the only one. A router, a worker or the Tool
Gateway constructs a `ServiceContext` and calls a service; none of them may reach `repository`,
which is why it is absent from this module and stays absent (ADR-0002, contract §13).
"""

from app.contexts.work.authorization import ActorReach, reach_of
from app.contexts.work.commands import (
    AssignWork,
    ChangeDependencyStatus,
    ChangeMilestoneStatus,
    ChangeProjectStatus,
    ChangeProjectVisibility,
    ChangeWorkStatus,
    ChangeWorkVisibility,
    CreateDependency,
    CreateMilestone,
    CreateProject,
    CreateWork,
    EndAssignment,
    ReassignOwner,
    SetOwner,
    UpdateMilestone,
    UpdateProject,
    UpdateWork,
)
from app.contexts.work.domain import (
    AssignmentRole,
    AssignmentStatus,
    DependencyEdge,
    DependencyKind,
    DependencyStatus,
    Endpoint,
    MilestoneStatus,
    ProjectStatus,
    Source,
    Visibility,
    WorkPartition,
    WorkPriority,
    WorkStatus,
    WorkType,
    current_owner,
    partition_of,
)
from app.contexts.work.models import (
    Dependency,
    Milestone,
    Project,
    Work,
    WorkAssignment,
)
from app.contexts.work.queries import (
    ProjectFilter,
    ProjectPage,
    WorkFilter,
    WorkPage,
    WorkReference,
    get_dependency,
    get_milestone,
    get_project,
    get_work,
    list_assignments,
    list_dependencies_of_work,
    list_milestones,
    list_projects,
    list_work,
    work_references,
)
from app.contexts.work.references import assert_project_exists, assert_work_exists
from app.contexts.work.services import (
    AssignmentService,
    DependencyService,
    MilestoneService,
    ProjectService,
    ServiceContext,
    WorkService,
)
from app.contexts.work.similarity import (
    MIN_SIMILARITY,
    SimilarWork,
    find_similar_work,
)
from app.platform.errors import DomainRuleViolation, EntityNotFound
from app.platform.partial import UNSET

__all__ = [
    "reach_of",
    "ActorReach",
    "find_similar_work",
    "SimilarWork",
    "work_references",
    "WorkReference",
    "MIN_SIMILARITY",
    "assert_work_exists",
    "assert_project_exists",
    "UNSET",
    "AssignWork",
    "AssignmentRole",
    "AssignmentService",
    "AssignmentStatus",
    "ChangeDependencyStatus",
    "ChangeMilestoneStatus",
    "ChangeProjectStatus",
    "ChangeProjectVisibility",
    "ChangeWorkStatus",
    "ChangeWorkVisibility",
    "CreateDependency",
    "CreateMilestone",
    "CreateProject",
    "CreateWork",
    "Dependency",
    "DependencyEdge",
    "DependencyKind",
    "DependencyService",
    "DependencyStatus",
    "DomainRuleViolation",
    "EndAssignment",
    "Endpoint",
    "EntityNotFound",
    "Milestone",
    "MilestoneService",
    "MilestoneStatus",
    "Project",
    "ProjectService",
    "ProjectStatus",
    "ReassignOwner",
    "SetOwner",
    "ServiceContext",
    "Source",
    "Visibility",
    "WorkPriority",
    "WorkType",
    "UpdateMilestone",
    "UpdateProject",
    "UpdateWork",
    "Work",
    "WorkAssignment",
    "ProjectFilter",
    "ProjectPage",
    "WorkFilter",
    "WorkPage",
    "WorkPartition",
    "WorkService",
    "WorkStatus",
    "current_owner",
    "get_dependency",
    "get_milestone",
    "get_project",
    "get_work",
    "list_assignments",
    "list_dependencies_of_work",
    "list_milestones",
    "list_projects",
    "list_work",
    "partition_of",
]
